name: CI Pipeline

on:
  push:
    branches:
      - main
      - yana
      - aadit
      - akshay
      - alexia
  pull_request:
    branches:
      - main
      - yana
      - aadit
      - akshay
      - alexia

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python on Windows
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests on Windows
      run: pytest

    - name: Run flake8
      run: |
        flake8 .

    - name: Check code formatting with black
      run: |
        black --check .

    - name: Check for unused dependencies
      run: |
      pip-check

    - name: Run tests
      run: pytest

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python on macOS
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests on macOS
      run: pytest
    
    - name: Run flake8
        run: |
          flake8 .

    - name: Check code formatting with black
      run: |
        black --check .

    - name: Check for unused dependencies
      run: |
      pip-check

    - name: Run tests
      run: pytest